### ISSUE TITLE
Document using plugin from yaml

### ISSUE THREAD

**Issue by fire** [indix/gocd-s3-artifacts#60]
Hi indix,

Could you document how to use from yaml?

https://github.com/tomzo/gocd-yaml-config-plugin#plugin

Thank you.

**Comment by luckyrat** [comment]
For publishing to S3, the secret sauce is how the array of source and destinations needs to be represented - a string of JSON. So this example task works for me:

```
  tasks:
     - plugin:
         options:
             sourceDestinations: "[{source: 'dist/*', destination: ''}]"
             destinationPrefix: "/"
             artifactsBucket: "optional-bucket-name-to-override-env-variable"
         run_if: passed
         configuration:
             id: indix.s3publish
             version: 1
```
